server {
    listen 80;
    listen [::]:80;

    server_name ansimsori.ai www.ansimsori.ai
                ansimsori.com www.ansimsori.com
                ansimsori.co.kr www.ansimsori.co.kr
                ansimsori.kr www.ansimsori.kr;

    root /home/webdev;
    index index.html;

    access_log /var/log/nginx/ansimsori.access.log;
    error_log /var/log/nginx/ansimsori.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
