server {
    listen 80;
    listen [::]:80;

    server_name ansimsori.ai www.ansimsori.ai
                ansimsori.com www.ansimsori.com
                ansimsori.co.kr www.ansimsori.co.kr
                ansimsori.kr www.ansimsori.kr;

    return 301 https://www.ansimsori.ai$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name ansimsori.ai
                ansimsori.com www.ansimsori.com
                ansimsori.co.kr www.ansimsori.co.kr
                ansimsori.kr www.ansimsori.kr;

    ssl_certificate /etc/letsencrypt/live/ansimsori.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ansimsori.ai/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://www.ansimsori.ai$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name www.ansimsori.ai;

    root /home/webdev;
    index index.html;

    access_log /var/log/nginx/ansimsori.access.log;
    error_log /var/log/nginx/ansimsori.error.log;

    ssl_certificate /etc/letsencrypt/live/ansimsori.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ansimsori.ai/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
